import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ConfigProvider } from 'antd'

import StyledComponentsRegistry from "../lib/AntdRegistry"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Financial Advisor',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={`${inter.className} bg-gray-50 text-gray-950 relative`}
        >
          <StyledComponentsRegistry>
            <ConfigProvider>
              {children}
            </ConfigProvider>
          </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;